version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
clone_depth: 1
clone_folder: c:\MP\
init:
- cmd: 
cache: packages
environment:
  email:
    secure: dkWdmOxf3t/x2H0gEo1GurKM8Due1idnog5VJtUlSEA=
  token:
    secure: FfCpqsH/V1r7PoXHkMcJpW7kWiQ6rQaedlH2L8smyeY=
build_script:
- cmd: >-
    dotnet --info

    c:\mp\.nuget\nuget.exe update -self
    
    c:\mp\.nuget\nuget.exe restore
    
    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" MissionPlanner.sln /m /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    
    dir c:\mp\bin\Release\net461

    cd bin\Release\net461

    for /f %%f in ('dir /a-d /b plugins') do if exist .\%%f del .\plugins\%%f

    set PATH=c:\cygwin\bin;%PATH%

    7z a -tzip ..\..\..\MissionPlannerBeta.zip *  

    cd ..

    c:\cygwin\bin\find.exe net461 -type f -print0 | xargs.exe -i -0 md5sum.exe '{}' > checksums.txt

    copy checksums.txt c:\mp\

    cd c:\mp\

    cov-build.exe --dir cov-int msbuild.exe MissionPlanner.sln /m /p:Configuration=Debug /l:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    7z a -tzip MissionPlannerCov-int.zip c:\mp\cov-int 

    curl --form %token% --form %email% --form file=@MissionPlannerCov-int.zip --form version="%APPVEYOR_BUILD_VERSION%" --form description="" https://scan.coverity.com/builds?project=ArduPilot%2FMissionPlanner

test: off
artifacts:
- path: MissionPlannerCov-int.zip
  name: MissionPlannerCov-int
- path: MissionPlannerBeta.zip
  name: MissionPlannerBeta
- path: checksums.txt
  name: checksums
deploy: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/c7f1e74edef028cfa905
  method: POST
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false